// One benefit of using layouts in Next.js is that on navigation, only the page components
// update while the layout won't re-render. This is called partial rendering which preserves
// client-side React state in the layout when transitioning between pages. Use a .layout for any route
// Thsi root layout is mandatory and is shared by all pages in the app

import './globals.css';
import { lato } from '@/app/ui/fonts';
import NavBar from './ui/navbar';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      {/* <body>{children}</body> */}
      <body className={lato.className}>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
